replicaCount: 1

image:
  repository: dockerhub.ebi.ac.uk/gwas/gwas-mcp
  tag: "1.0.6"
  pullPolicy: IfNotPresent

service:
  name: gwas-mcp
  type: NodePort
  port: 80
  containerPort: 8000
  metricsPort: 9464

ingress:
  name: gwas-mcp
  annotations: {}
  path: "/gwas/mcp"
  mcpPath: "/gwas/mcp"

env:
  apiBaseUrl: "http://gwas-rest-api.gwas.svc.cluster.local:8080/gwas/rest/api"
  httpProxy: "http://hh-wwwcache.ebi.ac.uk:3128"

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 128Mi
